### PR TITLE
Fix: Forgot to import codecs

### PR DESCRIPTION
**Pull request by hongquan**
Fix a missing import, which makes parsers unusable.

Complement a test case for "create".

### CODE REVIEW

**Comment by mauricioabreu** [comment]
Wow! Thank you @hongquan

**Comment by mauricioabreu** [comment]
Do you need a new release @hongquan ?

**Comment by hongquan** [comment]
@mauricioabreu Please do.

**Comment by mauricioabreu** [comment]
@hongquan new version is available. Thank you!

**Pull request merged**
